Userstarsrepo
WildCodeSchool/2103-lille-js-p2-g3-github pull request #13
Opened 2021-04-19 18:53 UTC by Erriep

feature API five bigger stars repository filter and style + add axios…

2021-04-20 07:27 UTC, Hacene010 submitted a review, later dismissed

2021-04-21 10:53 UTC, LoicBrassart requested changes
Which styling tool do you want to use ?

2021-04-21 10:53 UTC, LoicBrassart commented on package.json
> +    "styled-components": "^5.2.3",
One or the other, but not both ;-)

2021-04-21 10:53 UTC, LoicBrassart commented on src/components/UserStarsRepo.scss
> +.UserStarsRepo {
Inconcistent with the addition of `styled-components`

2021-04-21 12:14 UTC, Hacene010 approved these changes

2021-04-22 06:54 UTC, LoicBrassart approved these changes
No more Evil

2021-04-22 06:56 UTC, merged