Home
WildCodeSchool/2103-lille-js-p2-g3-github pull request #2
Opened 2021-04-14 13:40 UTC by Hacene010

2021-04-14 13:58 UTC, christopheluc62 submitted a review, later dismissed

2021-04-14 14:09 UTC, LoicBrassart requested changes
Minor Evils found ! 
Please fix it :smiling_imp:

2021-04-14 14:09 UTC, LoicBrassart commented on src/components/scss/Description.scss
> +  flex-direction: row-reverse; /*Pour placer la description sur la gauche*/
Comments in English plz

2021-04-14 14:09 UTC, LoicBrassart commented on src/components/scss/Description.scss
> +
Useless empty lines

2021-04-14 14:09 UTC, LoicBrassart commented on src/components/scss/Description.scss
> +    padding-top: 0;
Indentation

2021-04-14 15:02 UTC, Hacene010 commented on src/components/scss/Description.scss
> +  flex-direction: row-reverse; /*Pour placer la description sur la gauche*/
fixed it

2021-04-14 15:04 UTC, Hacene010 commented on src/components/scss/Description.scss
> +    padding-top: 0;
all fixed

2021-04-14 17:11 UTC, christopheluc62 approved these changes

2021-04-15 12:14 UTC, LoicBrassart approved these changes
Much better, No More Evil ;-)

2021-04-15 12:16 UTC, merged