Activity user
WildCodeSchool/2103-lille-js-p2-g3-github pull request #39
Opened 2021-05-01 20:35 UTC by Erriep

Implementation Function User activity with corresponding icons and formatting the user account creation date

2021-05-02 07:35 UTC, ThaiBangHOANG submitted a review, later dismissed

2021-05-03 06:49 UTC, LoicBrassart requested changes
One fix and we're good!

2021-05-03 06:49 UTC, LoicBrassart commented on src/components/UserInfo.jsx
> +      image.src = `../img/${formActivity}.png`;
Wait, what !?
Up to now I was very proud of you <3
Why don't you do this directly in the render of this component ? Something like `<img src=`../img/${formatActivity}.png` />` ?

2021-05-03 08:18 UTC, ThaiBangHOANG approved these changes

2021-05-03 08:27 UTC, LoicBrassart approved these changes
Much better ;-)

2021-05-03 08:38 UTC, merged